"""FIXTURES_V1 battery digest — the identity of the public F evidence.

Role:
    Computes `fixtures_digest()`, the sha256 that identifies the whole fixture package. It is a
    declared input of the run closure and enters `config_hash` (contract 3.11, 10), so a fixture
    edit changes the candidate's identity and can never pass unnoticed.
Used by:
    `tools.mem01_verify.run_identity.build_closure` (as `fixtures_digest`), the runner's machine
    block (`fixtures_digest` field), the release manifest, and `GateContext.fixtures_digest`.
Depends on:
    `tools.mem01_verify.hashing` (`sha256_file`, `canonical_lines_digest` — the frozen §3.10
    digest primitives) and `pathlib`. It reads the fixture `.py` files from disk and imports
    nothing from the fixture modules, so it stays computable even while a battery is being
    authored — which is also why the `FIXTURES_V1` tag is NOT aliased here from
    `vis_matrix_a.FIXTURES_VERSION`: it belongs to the batteries that emit it.
Key invariants:
    - The digest is computed AT CALL TIME from the files on disk, never from a cached constant
      and never from imported module objects.
    - Formula (frozen): sha256 over the concatenation of the bytewise-sorted lines
      `<posix relative path>\\t<sha256 of the file bytes>\\n`, one line per `.py` file in the
      fixture package, path relative to the fixture package directory.
    - `__pycache__` directories are excluded; only `.py` files participate. Fixture bytes that
      are GENERATED by a Python module are covered through that module; a fixture asset ever
      committed as a non-`.py` file under this package would NOT be covered and must either be
      generated from a module or added to the release manifest's hashed file list explicitly.
    - The result is a 64-character lowercase hex string.
    - This module hashes ITSELF too — editing `digest.py` changes the digest, by design.
"""

from __future__ import annotations

from pathlib import Path

from tools.mem01_verify.hashing import canonical_lines_digest, sha256_file

_FIXTURES_ROOT = Path(__file__).resolve().parent
_EXCLUDED_DIRS = frozenset({"__pycache__"})


def _fixture_source_files(root: Path) -> list[Path]:
    """Return every fixture `.py` file under `root`, excluding `__pycache__` directories."""
    return [
        path
        for path in root.rglob("*.py")
        if path.is_file() and _EXCLUDED_DIRS.isdisjoint(path.relative_to(root).parts)
    ]


def _digest_line(root: Path, path: Path) -> str:
    """Return the canonical `<posix relative path>\\t<sha256>\\n` line for one fixture file."""
    return f"{path.relative_to(root).as_posix()}\t{sha256_file(path)}\n"


def fixtures_digest() -> str:
    """Compute the FIXTURES_V1 digest of the fixture package as it exists on disk.

    The digest covers every `.py` file in `tools/mem01_verify/fixtures/` (recursively, minus
    `__pycache__`). Each file contributes one line `<posix relative path>\\t<sha256>\\n`, the
    lines are sorted bytewise, concatenated, and hashed with sha256.

    Returns:
        The 64-character lowercase hex sha256 of the sorted, concatenated lines.
    """
    lines = [_digest_line(_FIXTURES_ROOT, path) for path in _fixture_source_files(_FIXTURES_ROOT)]
    return canonical_lines_digest(lines)
